language: php

os:
  - linux

# Travis support wrote "Ubuntu 14.04 reached EOL on April 30th, 2019,
# ... we've been slowly rolling out changes to make Xenial builds ..."
# https://blog.travis-ci.com/2019-04-15-xenial-default-build-environment
# https://docs.travis-ci.com/user/reference/xenial/#services-disabled-by-default.
services:
  - mysql

jobs:
  fast_finish: true
  include:
    - env: DB=mysql; MW=REL1_31; TYPE=coverage; PHPUNIT=6.5.*
      php: 7.0
    - env: DB=sqlite; MW=REL1_32; PHPUNIT=6.5.*
      php: 7.1
    - env: DB=sqlite; MW=REL1_33; PHPUNIT=6.5.*
      php: 7.2
    - env: DB=sqlite; MW=master; PHPUNIT=6.5.*
      php: 7.3
  allow_failures:
    - env: DB=sqlite; MW=master; PHPUNIT=6.5.*

install:
  - bash ./tests/travis/install-mediawiki.sh
  - bash ./tests/travis/install-semantic-cite.sh

script:
  - bash ./tests/travis/run-tests.sh

after_success:
  - bash ./tests/travis/upload-coverage-report.sh

notifications:
  email:
    on_success: change
    on_failure: always

cache:
  directories:
    - $HOME/.composer/cache
