# http://docs.travis-ci.com/user/workers/container-based-infrastructure/
sudo: false

language: php

env:
  - THENEEDFORTHIS=FAIL

matrix:
  fast_finish: true
  include:
    - env: DB=mysql; MW=REL1_27; TYPE=coverage
      php: 5.6
    - env: DB=mysql; MW=REL1_27;
      php: 5.5
    - env: DB=sqlite; MW=REL1_28; SITELANG=ja
      php: 5.6
    - env: DB=sqlite; MW=master; PHPUNIT=4.8.*
      php: '7'
  exclude:
    - env: THENEEDFORTHIS=FAIL
  allow_failures:
    - env: THENEEDFORTHIS=FAIL

install:
  - bash ./tests/travis/install-mediawiki.sh
  - bash ./tests/travis/install-semantic-cite.sh

script:
  - bash ./tests/travis/run-tests.sh

after_success:
  - bash ./tests/travis/upload-coverage-report.sh

notifications:
  email:
    on_success: change
    on_failure: always
  irc:
    channels:
      - "chat.freenode.net#semantic-mediawiki"
    on_success: change
    on_failure: always

cache:
  directories:
    - $HOME/.composer/cache
